include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/build/**"
  errors:
    # No bloquear CI por estos avisos comunes
    unused_field: ignore
    dangling_library_doc_comments: ignore
    unused_import: ignore
    prefer_const_constructors: ignore
    unnecessary_string_interpolations: ignore
    prefer_final_fields: ignore

linter:
  rules:
    # Permitimos prints durante desarrollo (no en release)
    avoid_print: false
